version: 2

defaults: &defaults
  machine: true
  steps:
    - checkout
    - run:
        name: Docker build and push
        command: |
          cd servers/$SERVER
          VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g')
          echo $VERSION
          docker build -t $DOCKER_USER/$SERVER .
          docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
          # docker push $DOCKER_USER/$SERVER:$VERSION
          docker push $DOCKER_USER/$SERVER:latest

jobs:
  build-sycn-repo:
    <<: *defaults
    environment:
      SERVER: sync-gitlab-repo-from-gogs

  build-slack-command:
    <<: *defaults
    environment:
      SERVER: slack-command-gitlab-ci

workflows:
  version: 2
  build:
    jobs:
      - build-sycn-repo
      - build-slack-command
