version: 2

defaults: &defaults
  machine: true
  steps:
    - checkout
    - run:
        name: Docker build and push
        command: |
          cd servers/$SERVER
          docker build -t $DOCKER_USER/$SERVER .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/$SERVER:latest

jobs:
  build-sycn-repo:
    <<: *defaults
    environment:
      SERVER: sync-gitlab-repo-from-gogs
      # VERSION:

  build-slack-command:
    <<: *defaults
    environment:
      SERVER: slack-command-gitlab-ci
      # VERSION:

workflows:
  version: 2
  build:
    jobs:
      - build-sycn-repo
      - build-slack-command
